### ISSUE TITLE
Watch for oplog to get notified of incoming publishes when using Mongodb instead of polling

### ISSUE THREAD

**Issue by CarlLee** [mcollina/ascoltatori#100]
Current version use polling from Mongodb to acquire latest updates on topics, this will cause problem if application scales up and potentially crash Mongodb cluster.

I found this little [library](https://github.com/TorchlightSoftware/mongo-watch) that monitors oplog of Mongodb cluster to get notified of changes in the collections, but it relies on getting access to the oplog files which is not always feasible.

Though it's not perfect solution, I think at least there should be an alternative to polling. Maybe add a parameter to ask for pushing from instead of polling from Mongodb.

**Comment by smeijer** [comment]
This topic has been closed, but I don't see the answer to the question.

Was it indeed correct? Does this `tailable cursor` work? Or should the new `mongo change streams` be used instead? (A lot has changed in over 3 years).

If this `tailable cursor` was indeed correct, I don't understand why [`Meteor`](https://github.com/meteor/meteor/) wouldn't have used it instead of `Oplog` tailing.
