### ISSUE TITLE
MQTT: reconnects won't resubscribe

### ISSUE THREAD

**Issue by oshoemaker** [mcollina/ascoltatori#113]
In the event of a MQTT reconnect the mqtt_ascoltatore.js won't add the subscribes.  I have attempted to fix this by wrapping the subscribes in the 'ready' event.  Unfortunately the clients 'subs_counter' prevents this.  

One workaround is to patch the this._client.on("connect"... and add a that._subs_counter.clear(); to it.  That way, if you wrap the subscribes inside of ascoltatore.on('ready' the subscribes will be added.

Is there a better way to approach this issue?  It is important to us that the mqtt/ascoltatori client is resilient in the event of a mqtt server restart.

**Comment by mcollina** [comment]
The easiest fix is to pass the `clean: false` option, so that your parent broker keep your subscriptions across reconnects. This should be the preferred way, however a generic fix might be needed.

Given that inside the Ascoltatore we have the list of all subscribed topics, the actual fix should be to re-issue all these subscribes. Would you like to send a PR on this?

**Comment by oshoemaker** [comment]
Thanks for the quick response. This issue was exposed when the parent broker crashes or restarts. I will issue a pull request as this behavior should be implemented in the client.

**Comment by oshoemaker** [comment]
Test written and modifications committed.  Passed JSHint and tests.  Let me know if you need anything else.

**Comment by mcollina** [comment]
Fixed in 0.20.2.
