### ISSUE TITLE
remove domain support?

### ISSUE THREAD

**Issue by mcollina** [mcollina/ascoltatori#98]
Should we remove domain support?
Is this actually used by anybody?

If not, I'll be more than happy to remove it and avoid all the problems it causes.

**Comment by boneskull** [comment]
@mcollina I'm actually using it.

The problem is that Mocha is *incompatible* with domains.  Since I am very new to domains, I can't say why exactly, but I hope to get to the bottom of it through my usage of domains with ascoltatori.

However... I don't really understand the purpose of `registerDomain()`.  If you have a domain, you can simply add the resulting `ascoltatore` to it, since it's an `EventEmitter`.

**Comment by mcollina** [comment]
No, you cannot. You can add the Ascoltatore as an event emitter, but not
all the called functions. The registerDomain will make sure that all the
subscribers are called in the given domain.

Probably domains will never get removed though. If you need any change in
this area, just send a PR.
Il giorno lun 29 giu 2015 alle 06:12 Christopher Hiller <
notifications@github.com> ha scritto:
